### ISSUE TITLE
Password Protected site?

### ISSUE THREAD

**Issue by itsbrex** [joshuaiz/hexy#26]
Can't access the main site.

**Comment by joshuaiz** [comment]
@itsbrex hexy.io is currently down. In short every url with every hex code was being crawled which made it super expensive to host on Netlify. 

I may rebuild it if I have time but no eta at the moment.

**Comment by yelircaasi** [comment]
The URL should be removed from the github page unless/until it goes back up.

**Comment by joshuaiz** [comment]
@yelircaasi removed. I would love to spend time on this and get it back up but no eta as of now.
